apiVersion: v1
kind: Namespace
metadata:
  name: api

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 09d150e5-af03-4e9f-b63d-3e2a67d7f2eb   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: challenge5kv        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: sql-user
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: sql-password
          objectType: secret
          objectVersion: ""
    tenantId: c675cb6d-cbef-4abd-b8e7-f70a99137c2f               # The tenant ID of the key vault
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: api
spec:
  provider: azure                             
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: sql-user                           # data field to populate
      objectName: sql-user                        # name of the mounted content to sync; this could be the object name or the object alias
    secretName: sql-user                     # name of the Kubernetes secret object
    type: Opaque
---                           # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: api
spec:
  provider: azure                             
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: sql-password                           # data field to populate
      objectName: sql-password                        # name of the mounted content to sync; this could be the object name or the object alias
    secretName: sql-password                     # name of the Kubernetes secret object
    type: Opaque
---       