apiVersion: v1
kind: Namespace
metadata:
  name: api

---

kind: Secret
apiVersion: v1
metadata:
  name: sql-user
  namespace: api
data:
  SQL_USER: c3FsYWRtaW5vVXc4ODQ4
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: sql-password
  namespace: api
data:
  SQL_PASSWORD: YVgwdGc2WWEz
type: Opaque

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit
  namespace: api
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-view
  namespace: api
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "get", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-edit
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-edit
subjects:
- kind: Group
  namespace: api
  name: ed9e5880-4f91-445e-90f4-ab16ae0fc61d # api-devs

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-view
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-view
subjects:
- kind: Group
  namespace: api
  name: 1d2c02ac-eec1-4cdd-acc3-e3b6facc536d # web-devs
