apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poiapp
  template:
    metadata:
      labels:
        app: poiapp
    spec:
      containers:
      - name: poiapp
        image: registryouw8848.azurecr.io/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-user
              key: SQL_USER
        - name: SQL_PASSWORD
          value: "aX0tg6Ya3"
        - name: SQL_SERVER
          value: "sqlserverouw8848.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Local"
        - name: WEB_PORT
          value: "80"
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
---

apiVersion: v1
kind: Service
metadata:
  name: poiservice
spec:
  type: ClusterIP
  selector:
    app: poiapp
  ports:
  - port: 80
    targetPort: 80

