apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewerapp
  template:
    metadata:
      labels:
        app: tripviewerapp
    spec:
      containers:
      - name: tripviewerapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "65Mi"
            cpu: "100m"
        image: registryouw8848.azurecr.io/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://tripsservice.api"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofileservice.api"
       
---

apiVersion: v1
kind: Service
metadata:
  name: tripviewerservice
  namespace: web
spec:
  type: ClusterIP
  selector:
    app: tripviewerapp
  ports:
  - port: 80
    targetPort: 80

