apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofileapp
  template:
    metadata:
      labels:
        app: userprofileapp
    spec:
      containers:
      - name: userprofileapp
        image: registryouw8848.azurecr.io/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: kvsqluser
              key: sql-user
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kvsqlpassword
              key: sql-password
        - name: SQL_SERVER
          value: "sqlserverouw8848.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-challenge5kv-msi"
---

apiVersion: v1
kind: Service
metadata:
  name: userprofileservice
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: userprofileapp
  ports:
  - port: 80
    targetPort: 80

