apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofileapp
  template:
    metadata:
      labels:
        app: userprofileapp
    spec:
      containers:
      - name: userprofileapp
        image: registryouw8848.azurecr.io/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-user
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: "sqlserverouw8848.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
---

apiVersion: v1
kind: Service
metadata:
  name: userprofileservice
spec:
  type: ClusterIP
  selector:
    app: userprofileapp
  ports:
  - port: 80
    targetPort: 80

