apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-javaapp
  template:
    metadata:
      labels:
        app: user-javaapp
    spec:
      containers:
      - name: user-javaapp
        image: registryouw8848.azurecr.io/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-user
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: "sqlserverouw8848.database.windows.net"
---

apiVersion: v1
kind: Service
metadata:
  name: user-javaservice
spec:
  type: ClusterIP
  selector:
    app: user-javaapp
  ports:
  - port: 80
    targetPort: 80

